sudo: false
language: python
python:
- '2.7'
- '3.5'
- '3.6'
install:
- pip install -e .
- pip install -r test-requirements.txt
- if [[ $TRAVIS_PYTHON_VERSION == '3.6' ]]; then pip install mypy; fi
script:
- make test
- if [[ $TRAVIS_PYTHON_VERSION == '3.6' ]]; then make test_mypy; fi
deploy:
  provider: pypi
  user: lyftpypi
  password:
    secure: XtORTwAm/Fe4Vf9u9bugXJezTaPLlJlg88z9+VzgG+ccanqJAhrz5viM6lX4x1wQqWaccLwu7/GFHyeDrbqntEoqWXNVIca4Qxg5Neg1IQKNtw2LLL2hU8suUWUcF+7lY28NQT5gr9NE87bJt4PzKy0P7WIMuNKdNfgZ7IeBCxPm6KwRVDyvw/yzc9n/gK/N7UEQYHu3L+6HOjkmIi8nADItrDsc8263d1KqZtWRPbZCFwQSGqVOyO58u6dbMkLyI9qncXK7RnBZ3LEmhLfimpPG8ew7vMFSUWcScfj3X75ZPmJDYju0PDocnGqpWeayn7dWq/GSphDjKioYkOPleloI0PfSZPRG22iGu5H2w5/vR5wr4QQzwOJk7Xw8LDvaz4ckFmbrMgw3bzpsbiouM6ycb1FxAJjBLbjQneNcttu+1BMK+8tDlu8VbqbGuRSdKSlDOEoVyClzO844u8lpW9Os4enLmxEjeEb9pWIQe2Oy7WhAYmaVGpZNLabiACDNZEP9adKg4/hPhAUKST1Iqr710ANzHfhmnlyBOzxXwQwjFjJ+M5Jp1lRIEHIB09CSs3gSC5AACqnp6mvlReKCsPLA09U8g4pS+WzhBS+YJuYYuKw6iIm+r2V8TpAKPmsWgoLHt5er/4SpgtaBmTe1smftw3kmbRi3cVwmjvC9EXo=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: lyft/awspricing
